[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "chromium", "chromedriver"]

[phases.install]
cmds = ["pip3 install --break-system-packages -r requirements.txt"]

[start]
cmd = "python3 app.py"
