[phases.setup]
nixPkgs = [
    "nodejs_18",
    "chromium",
    "nss",
    "freetype",
    "harfbuzz",
    "ca-certificates",
    "fontconfig",
    "glib",
    "gtk3",
    "pango",
    "cairo",
    "atk",
    "gdk-pixbuf",
    "libdrm",
    "mesa",
    "xorg.libX11",
    "xorg.libXcomposite",
    "xorg.libXdamage",
    "xorg.libXext",
    "xorg.libXfixes",
    "xorg.libXrandr"
]

[phases.install]
cmds = [
    "export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true",
    "npm install --legacy-peer-deps"
]

[start]
cmd = "./start.sh"
